import type { Metadata } from "next";
import { Roboto, Crimson_Text } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "./css/app.css";

const roboto = Roboto({
  weight: '400',
  subsets: ["latin"] 
});

const crimsonText = Crimson_Text({
  weight: '400',
  subsets: ["latin"] 
});

export const metadata: Metadata = {
  title: "Ontego Hardware Finder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={[roboto.className, 'scretched'].join(' ')}>{children}</body>
    </html>
  );
}
